"""
columbia_messenger.py
Send messages to Columbia alumni via the alumni portal profile pages.

Each alumnus has a profile page on community.alumni.columbia.edu with a
"Message" button. This script visits each profile, clicks the button, and
fills in the subject + body generated by email_generator.py.

Usage via main.py:
  python main.py send columbia              # send to up to DAILY_LIMIT contacts
  python main.py send columbia --limit 10   # cap at 10
  python main.py send columbia --dry-run    # preview without sending

Standalone:
  python columbia_messenger.py --limit 5 --dry-run
"""

import asyncio
import logging
import os
import random
import time
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from playwright.async_api import async_playwright, BrowserContext, Page, TimeoutError as PwTimeout, Error as PwError

load_dotenv()

log = logging.getLogger(__name__)

PROFILE_BASE       = "https://community.alumni.columbia.edu"
PLAYWRIGHT_PROFILE = Path(__file__).parent / ".playwright_profile" / "columbia"
DAILY_LIMIT        = int(os.getenv("COLUMBIA_DAILY_LIMIT", os.getenv("DAILY_LIMIT", "15")))
COLUMBIA_UNI       = os.getenv("COLUMBIA_UNI", "")
COLUMBIA_PASSWORD  = os.getenv("COLUMBIA_PASSWORD", "")
LOGS_DIR           = Path(__file__).parent / "logs"


async def _extract_duo_code(page: Page) -> str:
    """
    Try to read the Duo Verified Push numeric code from the page or any Duo
    iframe. Polls for up to 15 s in case the iframe is still loading.
    Returns the code string, or '' if not found.
    """
    _DUO_SELECTORS = [
        "[data-testid='verification-code']",
        ".verification-code",
        ".passcode-value",
        "span.passcode",
    ]
    _NUMERIC_JS = """
        () => {
            const walk = (root) => {
                for (const el of root.querySelectorAll('div,span,p,h1,h2,h3,label,strong')) {
                    const t = (el.textContent || '').trim();
                    if (/^\\d{3,6}$/.test(t)) return t;
                }
                for (const sr of (root.shadowRoot ? [root.shadowRoot] : [])) {
                    const r = walk(sr);
                    if (r) return r;
                }
                return null;
            };
            return walk(document.body);
        }
    """

    for _attempt in range(6):   # poll up to ~15 s
        frames = [page, *page.frames]
        for frame in frames:
            # Try known selectors first
            for sel in _DUO_SELECTORS:
                try:
                    loc = frame.locator(sel).first
                    if await loc.count() > 0:
                        text = (await loc.inner_text(timeout=2_000)).strip()
                        if text and text.isdigit():
                            return text
                except Exception:
                    pass
            # Fallback: scan all text nodes for a standalone number
            try:
                result = await frame.evaluate(_NUMERIC_JS)
                if result:
                    return result
            except Exception:
                pass
        await asyncio.sleep(3)
    return ""


async def _ensure_logged_in(page: Page) -> bool:
    """
    Navigate to the portal home. If redirected to CAS login, authenticate.
    Returns True if we end up on the portal, False on failure.
    """
    try:
        await page.goto(PROFILE_BASE + "/s/", wait_until="domcontentloaded", timeout=30_000)
        await asyncio.sleep(2)
    except PwTimeout:
        pass
    except PwError as e:
        log.info(f"[columbia] Network error during login check: {e}")
        return False

    current = page.url
    if "login" in current or "cas.columbia.edu" in current or "shibboleth" in current:
        log.info("[portal] Session expired — logging in to Columbia portal...")
        try:
            uni_field = page.locator(
                "input#username, input[name='user'], input[name='uid'], input[type='text']"
            ).first
            await uni_field.fill(COLUMBIA_UNI, timeout=10_000)

            pw_field = page.locator(
                "input#password, input[name='password'], input[type='password']"
            ).first
            await pw_field.fill(COLUMBIA_PASSWORD, timeout=10_000)

            submit = page.locator(
                "button[type='submit'], input[type='submit'], "
                "button:has-text('Login'), button:has-text('Sign in')"
            ).first
            await submit.click(timeout=10_000)

            await asyncio.sleep(3)

            if "duo" in page.url.lower() or await page.locator("iframe[src*='duo']").count() > 0:
                log.info("[portal] Duo MFA detected — checking for verification code...")
                LOGS_DIR.mkdir(exist_ok=True)
                screenshot_path = LOGS_DIR / f"duo_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
                await page.screenshot(path=str(screenshot_path), full_page=True)
                log.info(f"[portal] Duo screenshot saved to: {screenshot_path}")
                code = await _extract_duo_code(page)
                if code:
                    log.info(f"[portal] *** Duo verification code: {code} *** (enter this in the Duo Mobile app)")
                else:
                    log.info("[portal] Could not extract code automatically — open the screenshot above to see it.")
                log.info("[portal] Waiting up to 5 minutes for Duo approval...")

            # Poll for the portal URL — handles cases where the redirect
            # already completed during the code-extraction step above.
            # Also clicks any "Continue" button that Duo shows post-approval.
            _deadline = 300  # seconds
            _interval = 5
            _waited   = 0
            while _waited < _deadline:
                _cur = page.url
                if "community.alumni.columbia.edu" in _cur:
                    break
                # Click "Continue" / "Proceed" if Duo is showing one
                for _frame in [page, *page.frames]:
                    try:
                        _btn = _frame.locator(
                            "button:has-text('Continue'), button:has-text('Proceed'), "
                            "a:has-text('Continue'), input[value='Continue']"
                        ).first
                        if await _btn.is_visible(timeout=500):
                            log.info("[portal] Clicking 'Continue' button after Duo approval...")
                            await _btn.click()
                            await asyncio.sleep(2)
                            break
                    except Exception:
                        pass
                if _waited > 0 and _waited % 30 == 0:
                    log.info(f"[portal] Still waiting for redirect ({_waited}s elapsed)... current URL: {_cur}")
                await asyncio.sleep(_interval)
                _waited += _interval
            else:
                raise Exception(
                    f"Timed out after {_deadline}s waiting for Columbia portal. "
                    f"Last URL: {page.url}"
                )
            log.info("[portal] Logged in successfully.")
        except Exception as e:
            log.info(f"[portal] Login failed: {e}")
            return False

    return True


# ---------------------------------------------------------------------------
# Shadow DOM helpers
# ---------------------------------------------------------------------------

_FIND_BUTTON_JS = """
(labelText) => {
    function findButton(root) {
        for (const el of root.querySelectorAll('button, a[role="button"], lightning-button, c-button')) {
            const text = (el.textContent || el.innerText || '').trim().toLowerCase();
            if (text === labelText.toLowerCase() || text.startsWith(labelText.toLowerCase())) {
                return el;
            }
        }
        for (const el of root.querySelectorAll('*')) {
            if (el.shadowRoot) {
                const found = findButton(el.shadowRoot);
                if (found) return found;
            }
        }
        return null;
    }
    return findButton(document);
}
"""

_FIND_INPUT_JS = """
(selector) => {
    function findEl(root) {
        const el = root.querySelector(selector);
        if (el) return el;
        for (const child of root.querySelectorAll('*')) {
            if (child.shadowRoot) {
                const found = findEl(child.shadowRoot);
                if (found) return found;
            }
        }
        return null;
    }
    return findEl(document);
}
"""


async def _shadow_click(page: Page, label: str) -> bool:
    """Find a button by visible text (shadow DOM aware) and click it. Returns True on success."""
    el = await page.evaluate_handle(_FIND_BUTTON_JS, label)
    if el:
        obj = el.as_element()
        if obj:
            await obj.scroll_into_view_if_needed()
            await obj.click()
            return True
    return False


async def _shadow_fill(page: Page, selector: str, value: str) -> bool:
    """Find an input/textarea by CSS selector (shadow DOM aware) and fill it."""
    el = await page.evaluate_handle(_FIND_INPUT_JS, selector)
    if el:
        obj = el.as_element()
        if obj:
            await obj.click()
            await obj.fill(value)
            return True
    return False


# ---------------------------------------------------------------------------
# Core: send one message
# ---------------------------------------------------------------------------

async def send_portal_message(
    page: Page,
    profile_url: str,
    subject: str,
    body: str,
    dry_run: bool = False,
) -> bool:
    """
    Navigate to a profile page, open the Message dialog, fill and send.
    Returns True on success.
    """
    try:
        await page.goto(profile_url, wait_until="networkidle", timeout=45_000)
        await asyncio.sleep(random.uniform(3.0, 5.0))
    except PwTimeout:
        # networkidle can time out on heavy LWC pages — continue anyway
        await asyncio.sleep(2.0)

    if dry_run:
        return True  # Stop here — don't interact with the page

    # Bail out fast if the portal returned "Invalid Page"
    try:
        body_text = await page.locator("body").inner_text(timeout=3_000)
        if "Invalid Page" in body_text or "Page Not Found" in body_text:
            log.info(f"    [portal] Invalid/not-found page: {profile_url}")
            return False
    except Exception:
        pass

    # --- Step 1: Find and click the Message button ---
    # Dump all visible button texts for debugging on first failure
    clicked = False
    for label in ["Message", "Send Message", "Send a Message", "Direct Message"]:
        try:
            if await _shadow_click(page, label):
                clicked = True
                break
        except Exception:
            pass

    if not clicked:
        # Fallback: Playwright locator (handles light DOM and simple shadow piercing)
        for selector in ["button:has-text('essage')", "[data-label*='essage']", "a:has-text('essage')"]:
            try:
                btn = page.locator(selector).first
                await btn.wait_for(timeout=4_000)
                await btn.click()
                clicked = True
                break
            except Exception:
                pass

    if not clicked:
        # Debug: dump button texts and screenshot so we can see what's on the page
        try:
            btns = await page.evaluate("""() => {
                function collect(root, out=[]) {
                    for (const el of root.querySelectorAll('button,a[role="button"]')) {
                        out.push((el.textContent||'').trim().slice(0,60));
                    }
                    for (const el of root.querySelectorAll('*')) {
                        if (el.shadowRoot) collect(el.shadowRoot, out);
                    }
                    return out;
                }
                return collect(document);
            }""")
            log.info(f"    [portal] Visible buttons: {[b for b in btns if b][:20]}")
        except Exception:
            pass
        try:
            screenshot_path = Path(__file__).parent / "debug_portal.png"
            await page.screenshot(path=str(screenshot_path))
            log.info(f"    [portal] Screenshot saved to {screenshot_path}")
        except Exception:
            pass
        log.info(f"    [portal] Could not find Message button on {profile_url}")
        return False

    await asyncio.sleep(random.uniform(1.5, 2.5))

    # --- Step 2: Fill subject ---
    subject_filled = False
    for sel in ["input[name='subject']", "input[placeholder*='ubject']",
                "input[name='Subject']", "input.subject", "lightning-input input"]:
        if await _shadow_fill(page, sel, subject):
            subject_filled = True
            break
    if not subject_filled:
        # Try pressing Tab to focus subject field if modal just opened
        try:
            await page.keyboard.press("Tab")
            await page.keyboard.type(subject)
            subject_filled = True
        except Exception:
            pass

    await asyncio.sleep(0.5)

    # --- Step 3: Fill body ---
    body_filled = False
    for sel in ["textarea[name='body']", "textarea[name='Body']", "textarea[name='message']",
                "textarea[placeholder*='essage']", "textarea", "div[contenteditable='true']"]:
        if await _shadow_fill(page, sel, body):
            body_filled = True
            break
    if not body_filled:
        log.info(f"    [portal] Could not fill message body on {profile_url}")
        return False

    await asyncio.sleep(0.5)

    # --- Step 4: Click Send ---
    sent = False
    for label in ["Send", "Send Message", "Submit"]:
        try:
            if await _shadow_click(page, label):
                sent = True
                break
        except Exception:
            pass

    if not sent:
        try:
            btn = page.locator("button:has-text('Send')").last
            await btn.click()
            sent = True
        except Exception:
            pass

    if not sent:
        log.info(f"    [portal] Could not click Send on {profile_url}")
        return False

    await asyncio.sleep(random.uniform(1.5, 2.0))
    return True


# ---------------------------------------------------------------------------
# Batch runner
# ---------------------------------------------------------------------------

async def run_batch(limit: int = None, dry_run: bool = False, headless: bool = False):
    from database import (
        init_db, get_pending_columbia_contacts,
        mark_columbia_sent, mark_columbia_failed,
        how_many_columbia_sent_today,
    )
    from email_generator import generate_email

    init_db()

    sent_today = how_many_columbia_sent_today()
    cap = limit if limit else DAILY_LIMIT
    remaining = cap - sent_today

    if remaining <= 0:
        log.info(f"[portal] Columbia daily limit ({cap}) already reached. Come back tomorrow!")
        return

    contacts = get_pending_columbia_contacts(limit=remaining)
    if not contacts:
        log.info("[portal] No Columbia contacts with portal profile URLs pending.")
        return

    log.info(f"{'[DRY RUN] ' if dry_run else ''}[portal] Sending to {len(contacts)} Columbia alumni "
             f"(limit: {cap}/day, sent today: {sent_today})")

    PLAYWRIGHT_PROFILE.mkdir(parents=True, exist_ok=True)

    async with async_playwright() as pw:
        context: BrowserContext = await pw.chromium.launch_persistent_context(
            str(PLAYWRIGHT_PROFILE),
            headless=headless,
            args=["--disable-blink-features=AutomationControlled"],
            viewport={"width": 1280, "height": 900},
        )
        page: Page = await context.new_page()

        # Make sure the session is alive before starting the batch
        if not await _ensure_logged_in(page):
            log.info("[portal] Could not log in — aborting batch.")
            await context.close()
            return

        for i, contact in enumerate(contacts, 1):
            name = f"{contact['first_name']} {contact.get('last_name', '')}"
            co   = contact.get("company", "?")
            path = contact.get("portal_profile_url", "")
            url  = PROFILE_BASE + path

            try:
                subject, body = generate_email(contact)
            except Exception as e:
                log.info(f"[{i}/{len(contacts)}] {name} — email gen failed: {e}")
                mark_columbia_failed(contact["id"], str(e))
                continue

            role = contact.get("role") or "(no role)"
            log.info(f"[{i}/{len(contacts)}] {name} | {role} @ {co}")
            log.info(f"  Subject: {subject}")
            log.info(f"  Message:\n{body}")

            if dry_run:
                log.info("-" * 60)
                continue

            try:
                ok = await send_portal_message(page, url, subject, body, dry_run=dry_run)
            except Exception as e:
                log.info(f"  FAILED: {e}")
                mark_columbia_failed(contact["id"], str(e))
                continue

            if ok:
                mark_columbia_sent(contact["id"])
                log.info(f"  Sent!")
            else:
                mark_columbia_failed(contact["id"])
                log.info(f"  Failed (see above).")

            # Polite delay between messages (3-7s)
            await asyncio.sleep(random.uniform(3.0, 7.0))

        await context.close()

    log.info("[portal] Batch complete.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Columbia portal messenger")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--headless", action="store_true")
    a = parser.parse_args()
    asyncio.run(run_batch(limit=a.limit, dry_run=a.dry_run, headless=a.headless))
